### ISSUE TITLE
Doesn't seem to actually work

### ISSUE THREAD

**Issue by bruno-trindade** [Aleksefo/react-native-webp-format#1]
React Native version 0.62.2.  Have the npm package and pod installed, but the image doesn't actually render.  When I export the image to PNG and require that one instead, it works, so the problem isn't with my code.

Podfile.lock:
```
  - libwebp (1.1.0):
    - libwebp/demux (= 1.1.0)
    - libwebp/mux (= 1.1.0)
    - libwebp/webp (= 1.1.0)
  - libwebp/demux (1.1.0):
    - libwebp/webp
  - libwebp/mux (1.1.0):
    - libwebp/demux
  - libwebp/webp (1.1.0)
```

yarn.lock:
```
react-native-webp-format@^1.0.1:
  version "1.0.1"
  resolved "https://registry.yarnpkg.com/react-native-webp-format/-/react-native-webp-format-1.0.1.tgz#00d7e2d173ab98f273d703f2eaebcb7839a2847a"
  integrity sha512-aU2DTaRvpeBSheE9FEzPqJ2BXgn+Us1rCPD6/zg86Z8NEeAMMdOx9fHAzTqZZM3+np5YYDJI+HgfTw410iBeWg==
```

Sample code:
```js
// Does not render, no errors or warnings.
<Image style={{ height: 300, flex: 1 }} source={require("./example.webp")} />

// Renders
<Image style={{ height: 300, flex: 1 }} source={require("./example.png")} />
```

**Comment by Aleksefo** [comment]
Hi @bruno-trindade , I'll test it with the new version of React Native and will check if the library needs updating.

**Comment by flikQ** [comment]
@Aleksefo seems to work ok on Android, just not on iOS.

**Comment by flikQ** [comment]
I am running: "react-native": "0.61.5",

**Comment by curtisc** [comment]
I'm seeing the same problem on iOS on react-native 0.61.4

**Comment by Aleksefo** [comment]
@bruno-trindade @flikQ @curtisc I've created a fresh project with RN 0.62.2 and it seems to work fine on both emulators and physical devices. I've included the example project(with webp and jpeg images) into the repository, would be great if you can try it out.

**Comment by r1skz3ro** [comment]
@flikQ I'm using the same version of react-native - `0.61.5` and everything works fine

**Comment by flikQ** [comment]
@Aleksefo @r1skz3ro stupidly I should have commented on this sooner. It started working shortly after my initial post, I think all I needed was a clean and to restart my packager for iOS to kick in. Apologies.

**Comment by Aleksefo** [comment]
@r1skz3ro Thanks for the input!
@flikQ glad to hear that, I'll update the README with more details :)

I hope everyone else was able to resolve the issues too.
If the issue persists, please attach the problematic webp file.

**Comment by JulianKingman** [comment]
@Aleksefo I couldn't get this to work in iOS (Expo 37, RN 0.62.13 I think). I had to add `pod 'ReactNativeWebPFormat', :path => '../node_modules/react-native-webp-format'` to the pod file, is that normal?

**Comment by Aleksefo** [comment]
@JulianKingman shouldn't be the case. Pod installation should be done automatically after running "pod install". Is it an ejected Expo project?
