### ISSUE TITLE
Not working with Expo on iOS 13 and below versions

### ISSUE THREAD

**Issue by ggepenyan** [Aleksefo/react-native-webp-format#23]
I'm using Expo sdk 44 version and webp images are not being loaded on iOS 13 and versions below. Webp images are loading nice on any other device and higher iOS versions. Is there any way I can fix this? I've tried to fix that with this package but still no any change. Maybe there are additional steps to make this package work with expo?

**Comment by Aleksefo** [comment]
I've updated the library to version 1.2.0. It might solve the issue.
