### ISSUE TITLE
Webp is not Working on android

### ISSUE THREAD

**Issue by aniketgupta8960** [Aleksefo/react-native-webp-format#26]
We have added the webp and it is working with IOS but on android it does not work

**Comment by iqqmuT** [comment]
Do you have `implementation 'com.facebook.fresco:webpsupport:2.5.0'` in your `android/app/build.gradle` as mentioned in the docs: https://reactnative.dev/docs/image#gif-and-webp-support-on-android ?

**Comment by MursiDirect** [comment]
I am using 'com.facebook.fresco:webpsupport:2.5.0'

but i get this error while building Assemble APK
Duplicate class com.facebook.imagepipeline.cache.BitmapMemoryCacheFactory found in modules jetified-imagepipeline-2.0.0-runtime (com.facebook.fresco:imagepipeline:2.0.0) and jetified-imagepipeline-base-2.5.0-runtime (com.facebook.fresco:imagepipeline-base:2.5.0)


Any solution, please?

**Comment by Aleksefo** [comment]
It seems like either you already have those libraries added as dependencies for another library, or another library adds them manually. Try removing the declaration of 
    implementation 'com.facebook.fresco:animated-webp:2.5.0'
    implementation 'com.facebook.fresco:webpsupport:2.5.0'
   
and try again.
