### ISSUE TITLE
Animated webp with react-native-fast-image library

### ISSUE THREAD

**Issue by Fedorrychkov** [Aleksefo/react-native-webp-format#7]
Hi all!
I have problems with fast image lib and animated webp, https://github.com/DylanVann/react-native-fast-image/issues/771

And i found this library and its still working, but with native Image component from React Native.
How i can use fast image with this dependencies? Could you explain it?

**Comment by Aleksefo** [comment]
Hi,
I don't think you can combine those two libraries.
